"""Generate a DRY_RUN-only human review queue from authority registry evidence."""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPORT_TYPE = "operator_relief_human_review_queue_v1"
REGISTRY_PATH = Path("Reports/operator_relief/authority_registry/protected_authority_registry.json")
DECISION_PACKET_ROOT = Path("Reports/operator_relief/decision_packets")
OUTPUT_PATH = Path("Reports/operator_relief/human_review_queue/human_review_queue.json")

QUEUE_STATUS_PENDING = "PENDING_HUMAN_REVIEW"
QUEUE_STATUS_PROTECTED = "PROTECTED_HUMAN_REVIEW"
QUEUE_STATUS_DEPENDENCY_ONLY = "DEPENDENCY_ONLY_REVIEW"


@dataclass(frozen=True)
class HumanReviewQueueResult:
    report_type: str
    generated_at: str
    executable: bool
    source_authority_registry: str
    source_decision_diff_reports: list[str]
    queue_items: list[dict[str, Any]]
    protected_items: list[dict[str, Any]]
    workflow_conflict_items: list[dict[str, Any]]
    dependency_only_items: list[dict[str, Any]]
    non_canonical_dependency_items: list[dict[str, Any]]
    human_review_required_paths: list[str]
    do_not_touch_paths: list[str]
    safe_cleanup_paths: list[str]
    apply_ready_paths: list[str]
    recommended_next_action: str
    safety: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _normalize_path(path: str | Path) -> str:
    return Path(path).as_posix().lstrip("./")


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _unique(items: list[str]) -> list[str]:
    return sorted({item for item in items if item})


def _decision_diff_reports(repo_root: Path) -> list[str]:
    root = repo_root / DECISION_PACKET_ROOT
    if not root.exists():
        return []
    return [_normalize_path(path.relative_to(repo_root)) for path in sorted(root.glob("*decision_diff*.json"))]


def _workflow_item(rank: int, conflict: dict[str, Any]) -> dict[str, Any]:
    return {
        "rank": rank,
        "queue_type": "WORKFLOW_AUTHORITY_CONFLICT",
        "group_key": conflict.get("group_key"),
        "status": QUEUE_STATUS_PENDING,
        "human_decision_required": True,
        "apply_ready": False,
        "safe_to_generate_apply_packet_later": False,
        "likely_canonical_candidate": conflict.get("likely_canonical_candidate"),
        "paths": conflict.get("paths", []),
        "source_report": conflict.get("source_decision_diff_report"),
        "reason": conflict.get("reason"),
        "recommended_options": [
            "KEEP_WORKFLOWS_AS_CANONICAL",
            "MERGE_UNIQUE_CONTENT_FIRST",
            "KEEP_BOTH_FOR_NOW",
            "NEEDS_HUMAN_REVIEW",
        ],
        "recommended_next_action": "Human reviews conflict and records a decision; no APPLY packet is generated by this queue.",
    }


def _protected_item(rank: int, authority: dict[str, Any]) -> dict[str, Any]:
    return {
        "rank": rank,
        "queue_type": "PROTECTED_AUTHORITY",
        "group_key": authority.get("group_key"),
        "status": QUEUE_STATUS_PROTECTED,
        "human_decision_required": True,
        "apply_ready": False,
        "action": "DO_NOT_TOUCH_WITHOUT_HUMAN_REVIEW",
        "paths": authority.get("paths", []),
        "source_report": authority.get("source_decision_packet"),
        "reason": authority.get("reason"),
        "recommended_options": ["DO_NOT_TOUCH", "NEEDS_HUMAN_REVIEW"],
        "recommended_next_action": "Human review required before any future APPLY packet; this queue does not choose a canonical owner.",
    }


def _dependency_item(rank: int, dependency: dict[str, Any], non_canonical: bool = False) -> dict[str, Any]:
    return {
        "rank": rank,
        "queue_type": "NON_CANONICAL_DEPENDENCY" if non_canonical else "DEPENDENCY_ONLY_DOCUMENT",
        "path": dependency.get("path"),
        "source_group": dependency.get("source_group"),
        "status": QUEUE_STATUS_DEPENDENCY_ONLY,
        "human_decision_required": bool(non_canonical),
        "apply_ready": False,
        "cleanup_candidate": False,
        "classification": dependency.get("classification", "DEPENDENCY_OR_EVIDENCE_ONLY"),
        "reason": dependency.get("reason"),
        "recommended_next_action": "Keep as evidence/dependency unless a later human-approved packet says otherwise.",
    }


def build_queue(repo_root: Path) -> HumanReviewQueueResult:
    root = repo_root.resolve()
    registry = _load_json(root / REGISTRY_PATH)
    workflow_conflicts = list(registry.get("parked_workflow_authority_conflicts", []))
    protected_authorities = list(registry.get("protected_authorities", []))
    dependency_docs = list(registry.get("dependency_only_documents", []))
    non_canonical_dependencies = list(registry.get("non_canonical_dependencies", []))

    queue_items: list[dict[str, Any]] = []
    workflow_items: list[dict[str, Any]] = []
    protected_items: list[dict[str, Any]] = []
    dependency_items: list[dict[str, Any]] = []
    non_canonical_items: list[dict[str, Any]] = []
    rank = 1

    for conflict in workflow_conflicts:
        item = _workflow_item(rank, conflict)
        workflow_items.append(item)
        queue_items.append(item)
        rank += 1
    for authority in protected_authorities:
        item = _protected_item(rank, authority)
        protected_items.append(item)
        queue_items.append(item)
        rank += 1
    for dependency in dependency_docs:
        item = _dependency_item(rank, dependency)
        dependency_items.append(item)
        queue_items.append(item)
        rank += 1
    for dependency in non_canonical_dependencies:
        item = _dependency_item(rank, dependency, non_canonical=True)
        non_canonical_items.append(item)
        queue_items.append(item)
        rank += 1

    return HumanReviewQueueResult(
        report_type=REPORT_TYPE,
        generated_at=datetime.now(timezone.utc).isoformat(),
        executable=False,
        source_authority_registry=_normalize_path(REGISTRY_PATH),
        source_decision_diff_reports=registry.get("source_decision_diff_reports") or _decision_diff_reports(root),
        queue_items=queue_items,
        protected_items=protected_items,
        workflow_conflict_items=workflow_items,
        dependency_only_items=dependency_items,
        non_canonical_dependency_items=non_canonical_items,
        human_review_required_paths=_unique(list(registry.get("human_review_required_paths", []))),
        do_not_touch_paths=_unique(list(registry.get("do_not_touch_paths", []))),
        safe_cleanup_paths=[],
        apply_ready_paths=[],
        recommended_next_action="Review queue items and record human decisions; do not cleanup, canonicalize, or generate APPLY packets from this DRY_RUN queue.",
        safety={
            "executable": False,
            "dry_run_only": True,
            "cleanup_approved": False,
            "canonicalization_approved": False,
            "apply_packet_generated": False,
            "safe_cleanup_paths_empty": True,
            "apply_ready_paths_empty": True,
        },
    )


def _output_path(repo_root: Path) -> Path:
    root = repo_root.resolve()
    output = (root / OUTPUT_PATH).resolve()
    allowed_root = (root / OUTPUT_PATH.parent).resolve()
    if not (output.parent == allowed_root and allowed_root in output.parents):
        raise ValueError("Human review queue must be written under Reports/operator_relief/human_review_queue/.")
    return output


def write_report(result: HumanReviewQueueResult, repo_root: Path) -> Path:
    path = _output_path(repo_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(result.to_dict(), handle, indent=2, sort_keys=True)
        handle.write("\n")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate DRY_RUN-only human review queue.")
    parser.add_argument("--write-report", action="store_true", help="Write queue under Reports/operator_relief/human_review_queue/.")
    args = parser.parse_args(argv)

    result = build_queue(Path.cwd())
    payload: dict[str, Any] = result.to_dict()
    if args.write_report:
        payload["written_file"] = _normalize_path(write_report(result, Path.cwd()))
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
