[CmdletBinding()]
param(
    [string]$NextTarget = "Continue AI_OS automation workflow.",
    [string]$ReportDir = "automation/orchestration/reports/daily"
)

$ErrorActionPreference = "Stop"

$date = Get-Date -Format "yyyy-MM-dd"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$branch = git branch --show-current
$status = git status --short --branch
$latestCommits = git log --oneline -10

$files = Get-ChildItem -Recurse -File | Where-Object {
    $_.Extension -match '\.(ps1|md|json|yml|yaml|txt)$'
}

$content = $files | Get-Content
$wordCount = ($content | Measure-Object -Word).Words
$lineCount = ($content | Measure-Object -Line).Lines
$charCount = ($content | Measure-Object -Character).Characters
$fileCount = $files.Count

New-Item -ItemType Directory -Force $ReportDir | Out-Null
$reportPath = Join-Path $ReportDir ("AI_OS_DAILY_DEV_REPORT_{0}.md" -f $date)

$report = "# AI_OS Daily Dev Report - $date

## Timestamp
$timestamp

## Branch
$branch

## Git Status
$status

## Repository Telemetry
- File count: $fileCount
- Line count: $lineCount
- Word count: $wordCount
- Character count: $charCount

## Latest Commits
$latestCommits

## Next Target
$NextTarget

## Notes
- Daily report generated by AI_OS orchestration reporting helper.
- Generated report should be reviewed before commit.
"

$report | Out-File -FilePath $reportPath -Encoding utf8

Write-Host "AI_OS daily dev report generated:"
Write-Host $reportPath
Write-Host ""
Write-Host "Telemetry:"
Write-Host "- Files: $fileCount"
Write-Host "- Lines: $lineCount"
Write-Host "- Words: $wordCount"
Write-Host "- Characters: $charCount"